sources:
  - name: jaffle_shop
    database: raw
    schema: jaffle_shop
    tables:
      - name: customers
        columns:
          - name: id
            tests:
              - unique
              - not_null
                      
         

      
      - name: orders

  - name: stripe
    database: raw
    schema: stripe
    tables:
      - name: payment  